version: "3"
services:
  nginx:
    image: nginx:stable-alpine-slim
    container_name: nginx
    ports:
      - 8081:80
    volumes:
      - ./docker-nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
  php:
    build:
      context: ./docker-php-sample
    container_name: php
    depends_on:
      - dotnet
    env_file:
      - ./docker-php-sample/.env.example
    networks:
      - app-network
  dotnet:
    build:
      context: ./docker-dotnet-sample
    container_name: dotnet
    depends_on:
      - redis
    networks:
      - app-network
    env_file:
      - ./docker-dotnet-sample/.env.example
  redis:
    image: redis:7.4-rc2-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  redis_data:
